# Generated by Django 4.2.3 on 2023-07-04 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_feedback_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='userid',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
